linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: var-naming
